### ISSUE TITLE
Memory Control Options

### ISSUE THREAD

**Issue by Br0ther66** [dmcoles/ActionReplay5#9]
I've been a huge fan of Amiga Action Replay since the beginning. My enthusiasm for it led me, with the help of some friends, to translate the entire manual to Spanish languaje, so I could fully understand all the commands. I then published it on several sites of the "Amiga scene in Spain."

My Hardware:
Amiga 500
**ROM: 2.0 (37.175)**
DKB Megachip for 2MB of ChipMen
SupraDrive 500XP (Zulu SCSI) 2, 4, or 8 MB Fast RAM (Configurable via jumpers)
Action Replay DEMON v1

I recently read on the EAB forums that Phantasm said... some features like Memory Control only work with Kickstart 1.3.

I connected the external SCSI Supra Drive 500XP with only 4MB of Fast RAM. The Amiga boots up fine, but when I press the  button on Demon, the Amiga is freeze on the image currently displayed, and does nothing else. This works without problems with the original Datel Action Replay MKIII cartridge.

Perhaps some of you may think. How is possible this?, the MK III uses the $400000 memory area, which is within the 4 MB range.

The MK III is intelligent; it knows this, and automatically manages the SupraDrive memory without the user having to change anything, placing it between addresses $600000 and $A00000. As shown in this photo...

<a href="https://ibb.co/rK2YZ1xf"><img src="https://i.ibb.co/xKqWMR18/Demon-Issue-1-1.jpg" alt="Demon-Issue-1-1" border="0"></a>

The SysInfo program also confirms that the 4 MB of the SupraDrive are located between address $600000 and $A00000

<a href="https://ibb.co/3Vvm1NV"><img src="https://i.ibb.co/W70vny7/Demon-Issue-1-2.jpg" alt="Demon-Issue-1-2" border="0"></a>

This is curious; the MK III with 4 MB of Fast RAM gives a message of resident program that isn't true. But it always worked fine all these years.

<a href="https://ibb.co/Xkf3m6g2"><img src="https://i.ibb.co/4gwYBCGm/Demon-Issue-1-3.jpg" alt="Demon-Issue-1-3" border="0"></a>

**I configured the SupraDrive 500XP for only 2 MB of Fast RAM and it works with DEMON**, but we lose 2 MB very valuables.

The MK III with 2MB of Fast RAM (from SupraDrive) displays this screen in Memory Control...

<a href="https://ibb.co/TD3dpRmt"><img src="https://i.ibb.co/5XHwtvBL/Demon-Issue-1-4.jpg" alt="Demon-Issue-1-4" border="0"></a>

Demon appears different in Memory Control with 2MB of Fast RAM (from SupraDrive)

<a href="https://ibb.co/G46dqyT8"><img src="https://i.ibb.co/cSByj0LZ/Demon-Issue-1-5.jpg" alt="Demon-Issue-1-5" border="0"></a>

Would it be very complicated for you to add these features that the MK III already had?

Greetings from Sevilla (Spain) and thank you so much for all the work you are doing.
Francisco

**Comment by dmcoles** [comment]
Just to be clear are you saying that with action replay 3 on kickstart 2.0 you are able to use 4mb of fast ram? During my tests with winuae I wasnt able to see this working and my belief is that this only works on kickstart 1.3

**Comment by Br0ther66** [comment]
> Just to be clear are you saying that with action replay 3 on kickstart 2.0 you are able to use 4mb of fast ram? During my tests with winuae I wasnt able to see this working and my belief is that this only works on kickstart 1.3

Hey friend!

At least with the SupraDrive 500XP it works perfectly with 4MB of Fast RAM and Kickstart 2.0.

As I mentioned, the MK III automatically manages the SupraDrive memory, placing it between addresses $600000 to $A00000, as you can see in my photos.

WinUAE maybe not manage memory like the hardware combination of the SupraDrive 500XP + Action Replay MK III.

WinUAE, for 4MB, maybe will allocate memory from address $200000 to $600000, resulting in a conflict with the MK III memory located at address $400000. I don't think it would work with ROM 1.3 or any other version for this reason.

**Comment by Br0ther66** [comment]
I've experimented a lot with this and I can say that I've even managed to get it working with 6MB of Fast RAM.

4MB from SupraDrive 500XP - address $600000 to $A00000
2MB from A570 CD Interface - address $200000 to $400000

With this configuration, the only drawback is that the MKIII doesn't control the $200000 to $400000 area in certain commands.

<a href="https://ibb.co/1W7d8bm"><img src="https://i.ibb.co/BMcrqwC/20231203-204527.jpg" alt="20231203-204527" border="0"></a>

<a href="https://ibb.co/jmstMxY"><img src="https://i.ibb.co/dFxZ23v/20231203-204604.jpg" alt="20231203-204604" border="0"></a>

**Comment by Br0ther66** [comment]
Here's a screenshot with the A570 unconnected, just the SupraDrive with the avail command

<a href="https://ibb.co/hF9byntX"><img src="https://i.ibb.co/yFPtXMbh/Demon-Issue-1-6.jpg" alt="Demon-Issue-1-6" border="0"></a>

**Comment by Br0ther66** [comment]
Another photo I took with the A570 with 2MB memory expansion inside, for a total of 8MB.

8MB = 2MB Chip Memory + 4MB (SupraDrive) + 2MB (A570)

**ROM 2.0 (37.175)**
2MB Chip Memory ---------------------- address $000000 to $200000
4MB from SupraDrive 500XP -------- address $600000 to $A00000
2MB from A570 CD Interface -------- address $200000 to $400000

The $400000 memory area is free and Action Replay MKIII works perfectly. From what I can see, this is only possible on a real Amiga?

<a href="https://ibb.co/XZPsbwMQ"><img src="https://i.ibb.co/QFVNf5tg/ARMKIII-8-MB.jpg" alt="ARMKIII-8-MB" border="0"></a>

The thread is getting very hot (in the good sense of the words).

I think all this is possible because the hardware SupraDrive 500XP and Action Replay MK III work very well together.

The icing on the cake for this Amiga would be to make the necessary modifications to activate the C00000 memory area and obtain an extra of 1.5 MB Slow Fast RAM. That would be amazing!

**Comment by Br0ther66** [comment]
One more photo and we'll all be at ease.

<a href="https://ibb.co/hzkVBBv"><img src="https://i.ibb.co/0bkrCC3/ROM37175.jpg" alt="ROM37175" border="0"></a>

**Comment by dmcoles** [comment]
What version of the action replay rom is it running? 3.17 ?

**Comment by Br0ther66** [comment]
That's exactly it, dmcoles. I've updated the previous photo with the avail and version commands.

**Comment by dmcoles** [comment]
I will take another look and see what can be done

**Comment by Br0ther66** [comment]
Thank you so much. Since Action Replay 5, you've become my new idol, along with another new friend I made in France.

**Comment by Br0ther66** [comment]
Just a thought I'll leave hanging...
Is possible it will work (at least in my case) with any Kickstart. I can switch to Kickstart 3.2.2 via a toggle switch if you need me to test it.

If I can help you with the testing, inside my A-500 there are more components... an M-TEC 68020 with 4MB of 32-bit fast RAM. It's configurable via switches I installed on the back panel to use only the 68000, or only the 68020, or even just the 68020 with his 4MB. This works well even with the SupraDrive, and allows the use of Fast RAM in both, regardless of whether one RAM is 16-bit and the other 32-bit (4MB in the SupraDrive + 4MB in the M-TEC, totaling 8MB). I can turn on one memory, or the other, or both, as the consumer prefers ;-)

Externally, I can also install an A530 Turbo. I can configure with either 4 or 8MB. I have two port splitters to connect the A530 and Demon simultaneously, just like I do with the SupraDrive + A570 CD + Action Replay.
The 68030 is the good one, along with the math coprocessor. Everything runs at 40MHz and can use MMU.

As you can see, it's not a normal A-500, but using the 5 switches I installed on the left side of the back, I can return it to its factory settings, except for the ROM 1.3.

I'm here for any testing you need.

Finally, I'd like to add that I flashed Demon with the original 3.17 ROM from Datel and everything works just like it did with the original hardware.

And please excuse my English if it's not very good.

Cheers!

**Comment by dmcoles** [comment]
an updated dev build is available here https://filebin.net/hzz7vkz02nhksfbg which should fix this issue.

Please note this is a work in progress build and the link will only be valid for 6 days.

**Comment by Br0ther66** [comment]
Hi dmcoles, I quickly saw the new development version in my email client.

I've been at home very time, trying things out. Initially, when I turned on the Amiga, no detect the 4MB of SupraDrive fast memory.

Later, by pure chance, I think I managed to get it to recognize the memory and work. But give me some time to run all the tests properly, and be absolutely sure that I've managed to get it working in a somewhat strange way... and then I'll let you know for sure.

This is progressing!

Thank you so much for your work. I'll let you know soon.

**Comment by Br0ther66** [comment]
Hi dmcoles, I'll explain it step by step...

I updated Demon with the 5.2.1 development firmware, accessed it, and reset the preferences with `resetcfg`, followed by the `savecfg` command.

I turn on Amiga with Demon, and the SupraDrive configured for 4MB Fast RAM.

In the boot menu of ROM 2.0, I start from DH0 without a startup-sequence.

I press the button on the Demon, and execute the avail command. Not recognize the Fast memory;  the information appears all zero.

Press F3 key for first screen preferences 

Autoconfig appears as ON (MK III with 4 MB in SupraDrive show Autoconfig OFF).

External Memory displayed all values zero, and the "Add" option is OFF. (MKIII display External Memory $600000-$A00000, and the "Add" option  is ON).

Demon only lets me set Autoconfig OFF, but I can't get anything done. I can't enter any data in External Memory. "Add" can't be enabled.

X command and return to the Amiga Shell screen. Testing with SysInfo shows there is no Fast Memory.
......................................................................................................................................................................

Reset Amiga with Control+A+A

I restart Amiga from DH0 without startup-sequence.

I press the button on Demon, and Amiga freezes on the Shell screen and does nothing else.
.....................................................................................................................................................

Again, I reset Amiga with Control+A+A

**And when I tried to access to boot menu from ROM I made a mistake, only pressed the left mouse button and X-Copy appeared (by the Faststart method of Action Replay).**

**From the X-Copy screen**, I reset again with Control+A+A.

After disappear the Action Replay V boot logo, I pressed the button on Demon.

I pressed F3 for access to the first screen of preferences... "And Again Is The Force With You" ;-)
**Autoconfig is now OFF, "Add" is ON, and External Memory is $600000-$A00000 !!!**  (Exactly as it is in MK III)

<a href="https://ibb.co/Kcm1Yr3X"><img src="https://i.ibb.co/WNsTQ2Y6/Demon-Issue-1-09.jpg" alt="Demon-Issue-1-09" border="0"></a>

I return to Action Replay 5. I execute the avail command, and...

**WOW!** I have the 4MB of Fast Mem.

<a href="https://ibb.co/QvG6bfvj"><img src="https://i.ibb.co/b5nrWP5R/Demon-Issue-1-10.jpg" alt="Demon-Issue-1-10" border="0"></a>

At that same moment I execute savecfg with successfully.

From this point on, everything worked correctly in all resets using Control+A+A.
And most importantly, everything was fine when I turned the Amiga off and on, **thanks to having previously used savecfg**.

Testing with SysInfo shows that the 4MB of Fast Memory are present in $600000-$A00000

Perhaps the error lies in the programming that checks if the left mouse button is pressed to activate X-Copy when Action Replay 5 starts, and doesn't take into account the properties of the additional memory?

**Note:** From the Action Replay 5, using the Xcopy command and resetting does not work.

What I've described was really the second method I discovered by chance.
...........................................................................................................................

The first method I tried today, i already used with the previous version 5.2.0 and not work... but now work. And that's what comes next...

With the original MK III, I saved my preferences (including memory settings) to floppy disk using the save option on the second screen of preferences in the MK III (F3 followed by the Space Bar).

Although it may seem unimportant, I only disabled Burstnibbler Faststart.

I loaded my preferences from the original MK III into Demon, in the same way I would with MK III. I execute savecfg command, and after resetting the Amiga, Demon recognized the 4MB Fast memory, and apparently (at the moment I haven't done any more testing) it works fine.

Interesting, huh!

Regards

**Comment by dmcoles** [comment]
i've fixed some more issues relating to this, so please give this build a try

https://filebin.net/6vk692qdp4igas4b

- resetcfg should now reset the preferences to the default memory configuration (eg autoconfig and add mem are set according to what memory is present rather than just reset to fixed values)

- activating xcopy at boot should no longer interfere with the memory settings

- add mem options should now be enabled on all ks versions

**Comment by Br0ther66** [comment]
Hi

Something strange is happening with the latest firmware and the commands that operate on the chip memory.

In the photo, I put an example of how it recognizes 2MB of Chip Men, and SRIP only scans up to address 80000.

<img src="https://i.ibb.co/rK5XMKpf/Error-Demon-redimensionar.jpg" alt="Error-Demon-redimensionar" border="0">

It worked fine in the previous firmware, so keep that in mind.

Last night, I loaded the latest firmware using only the A500 and no other peripherals.

Then I connected everything in cascade: Demon, Supra, and A570.

Demon says I have the 6MB of Fast. 

External Memory 600000-A00000, and Autoconfig OFF. I execute savecfg, and it worked perfectly for a long time. Then I tested it with less memory, and there was a moment when it went completely crazy.

Now, for some reason, even after doing everything the same way I did initially and loading the firmware, I can't get it to work always correctly, not even after resetcfg.

I also tried using ROM 3.2.2, and initially it seemed to work fine with just the A500 and only 2MB Chip Men.

When I connected Supra with 4MB Fast Men, it didn't work. On the other hand, it did work with only 2MB.

This reminded me of when I first reported this same problem with ROM 2.0.

**Comment by Br0ther66** [comment]
Again, I've started from the beginning, reloading the development firmware from the 11th.

When I have the Amiga running with the 2MB (A570) + 4MB (Supra), Memory Control shows $200000-$400000. The MKIII with the same configuration shows Memory Control $600000-A00000.

After resetcfg, I check again, and it's still the same: $200000-$400000.

No problem, I can edit the addresses by setting them to $600000-$A00000, and everything seems to be working fine for now.

There's a small problem with savecfg. It doesn't seem to be saving the chip memory configuration correctly.

I saved the preferences to a floppy disk, and comparing it to another file that's working correctly, you can see in the file on the left saved with Demon, it has modified the fifth byte.


<a href="https://ibb.co/kg2MqBN2"><img src="https://i.ibb.co/KjxmVhTx/BadFile.jpg" alt="BadFile" border="0"></a>


18 is changed to 10. For 2MB chip, it should store a value of 18. This minor issue affects, for example, the Srip command, what now scan only up to address $80000, instead of up to $1FFFFF.

Loading a modified file with the value 18 makes everything work fine, as far as I can see so far.

Is it normal for the preferences file saved with Demon on floppy disk to be a few bytes longer than the original MK III file? The original is 65 bytes. Demon seems to have created a file with 4 more bytes, as seen in the image. Sometimes it adds 4 bytes, and other times it adds 2.

**Comment by dmcoles** [comment]
Thanks that's all useful info.. hopefully I should be able to get to the bottom of this with those details. 

Also I have sent you a PM on EAB

**Comment by dmcoles** [comment]
fixed in release V5.2.1
